import { Button, VerticalBox, ProgressIndicator, HorizontalBox, Palette, StyleMetrics } from "std-widgets.slint";
import { CompIntInput } from "comp_int_input.slint";

export enum UIState {
    Ready,
    Running,
    Success,
    Error,
}

export component AppWindow inherits Window {
    in-out property <UIState> state: Ready;
    in-out property <float> progress: 0.0;
    in-out property <int> pca_k: 10;
    in-out property <int> kmpp_k: 3;
    in-out property <int> kmpp_i: 3;

    out property <bool> show_default: state == UIState.Ready || state == UIState.Success;
    out property <bool> show_progress: state == UIState.Running;
    out property <bool> show_response: state == UIState.Success;
    out property <bool> show_error: state == UIState.Error;

    callback exe_data_mining();

    VerticalBox {
        StyledText {
            text: @markdown("**Dados Abertos, Microdados Enem 2024:** [link](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem)");
        }
        StyledText {
            text: @markdown("**Dados Abertos, Microdados Censo Escolar 2024:** [link](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-escolar)");
        }
        CompIntInput {
            text: @markdown("**PCA:** N° de componentes: ");
            enabled: show_default;
            value: root.pca_k;
        }
        CompIntInput {
            text: @markdown("**K-Means++:** N° de conjuntos: ");
            enabled: show_default;
            value: root.kmpp_k;
        }
        CompIntInput {
            text: @markdown("**K-Means++:** N° de iterações: ");
            enabled: show_default;
            value: root.kmpp_i;
        }
        Button {
            visible: show_default;
            text: "Executar mineração";
            clicked => {
                root.exe_data_mining();
            }
        }
        HorizontalBox {
            visible: show_progress;
            Text {
                text: "\{root.progress * 100}%";
            }
            ProgressIndicator {
                progress: progress;
            }
        }
    }
}
