import { Button, VerticalBox } from "std-widgets.slint";

// TODO: Execute button, Progress bar and Display
export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request_increase_value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request_increase_value();
            }
        }
    }
}